name: faceid
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.13.9=hc7d8306_100_cp313
  - python_abi=3.13=1_cp313
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py313hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.1
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.2.1
      - decorator==5.2.1
      - distro==1.9.0
      - dotenv==0.9.9
      - easydict==1.13
      - executing==2.2.1
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.1
      - google-auth-oauthlib==1.2.3
      - googleapis-common-protos==1.72.0
      - h11==0.14.0
      - httpcore==0.17.3
      - httplib2==0.31.0
      - httpx==0.24.1
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.37.2
      - insightface==0.7.3
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - langchain-core==1.1.0
      - langchain-openai==1.0.3
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.9
      - langsmith==0.4.46
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.2.6
      - oauthlib==3.3.1
      - onnx==1.19.1
      - onnxruntime==1.23.2
      - openai==2.8.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - prettytable==3.17.0
      - prompt-toolkit==3.0.52
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-telegram-bot==20.3
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - simsimd==6.5.3
      - six==1.17.0
      - sniffio==1.3.1
      - sounddevice==0.5.3
      - soundfile==0.13.1
      - stack-data==0.6.3
      - stringzilla==4.2.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - xxhash==3.6.0
      - zstandard==0.25.0
prefix: /Users/ivanhernandezgomez/miniconda3/envs/faceid
